name: Deploy to GitHub Pages
inputs:
  artifact-directory:
    description: 'The directory where the build artifacts are stored'
    default: './build'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload build directory
        path: ${{ inputs.artifact-directory }}

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
