name: Main Branch CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  jobs-build:
    name: Build React App
    uses: ./.github/workflows/jobs-build.yml

  jobs-deploy:
    name: Deploy to GitHub Pages
    uses: ./.github/workflows/jobs-deploy.yml
    needs: jobs-build
